#!/usr/bin/env python
import os
import sys
import time
import string
import argparse
import itertools
import multiprocessing
from subprocess import Popen, PIPE

def worker((cmd, timeout)):
    try:
        start = time.time()
        process = Popen(cmd, stdout=PIPE, stderr=PIPE)
        while True:
            if (time.time() - start) > timeout:
                print 'still running'
                try:process.kill()
                except: pass
                try:process.terminate()
                except: pass
                break
            status = process.poll()
            if status:
                print 'status:%s %s' % (status, ' '.join(cmd))
                break
    except KeyboardInterrupt:
        exit('bye')
    except Exception as error:
        print 'status:fatal %s' % ' '.join(cmd)

class Fuzz:
    def start(self, cmd, timeout, threads, path, chars, minC, maxC):
        pool = multiprocessing.Pool(int(threads))
        if path:
            for cmd in self._path_cmds(cmd, timeout, path):
                try:pool.map(worker, (cmd,))
                except KeyboardInterrupt: exit('bye')
        if chars != '':
            for cmd in self._char_cmds(cmd, timeout, chars, minC, maxC):
                try:pool.map(worker, (cmd,))
                except KeyboardInterrupt: exit('bye')

    def _path_cmds(self, cmd, timeout, path):
        orig_path = os.path.expanduser(path)
        for path, dirs, files in os.walk(orig_path):
            for f in files:
                file_name = os.path.join(path, f)
                yield [cmd.replace('#p', file_name).split(' '), timeout]

    def _char_cmds(self, cmd, timeout, chars, minC, maxC):
        for x in xrange(int(minC), int(maxC)):
            for y in itertools.permutations(chars, x):
                yield [cmd.replace('#c', ''.join(y)).split(' '), timeout]

if __name__ == '__main__':
    parse = argparse.ArgumentParser()
    parse.add_argument('cmd', help='cmd to run')
    parse.add_argument('-a', help='replace #c with ascii', action='store_true')
    parse.add_argument('-d', help='replace #c with digits', action='store_true')
    parse.add_argument('-s', help='replace #c with specials', action='store_true')
    parse.add_argument('-p', help='replace #p with file path', metavar=('DIR'))
    parse.add_argument('-minC', help='min length #c (DEFAULT:1)', default=1)
    parse.add_argument('-maxC', help='max length #c (DEFAULT:100)', default=100)
    parse.add_argument('-timeout', help='timeout (DEFAULT:2)', default=2)
    parse.add_argument('-threads', help='threads (DEFAULT:1)', default=1)
    if len(sys.argv) < 2:
        parse.print_help()
        exit()
    args = parse.parse_args()
    chars = ''
    if args.a:
        chars += string.ascii_letters
    if args.d:
        chars += string.digits
    if args.s:
        chars += string.punctuation + string.whitespace
    fuzz = Fuzz()
    fuzz.start(args.cmd, args.timeout, args.threads, args.p, chars,
        args.minC, args.maxC)
